on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version
        with:
          node-version: '16'
      - uses: actions/checkout@v4
      - run : npm install
      - run : node app.js