name: cicd-demo-actions
on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: node app.js